/* Focus Tracker: all business data is stored in Google Sheets via the Apps Script API. */
const savedSettings=JSON.parse(localStorage.getItem('focusTrackerSettings')||'{}');
const APP={apiUrl:localStorage.getItem('focusTrackerApiUrl')||'',categories:[],tasks:[],timer:null,activeTask:null,activeSession:null,activeDistraction:null,workCycles:0,settings:{work:Number(savedSettings.work)||25,shortBreak:Number(savedSettings.shortBreak)||5,longBreak:Number(savedSettings.longBreak)||15}};
const REASONS=['Рабочий чат','Комментарии в Битрикс','Встреча','Звонок','Отвлек сотрудник','Срочная задача','Личное дело','Усталость','Другое'];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mins=m=>{m=Number(m||0);return m>=60?`${(m/60).toFixed(m%60?1:0)} ч`:`${m} мин`};
function toast(msg){const e=$('#toast');e.textContent=msg;e.classList.add('show');clearTimeout(APP.toast);APP.toast=setTimeout(()=>e.classList.remove('show'),2800)}
async function api(action,data={}){if(!APP.apiUrl)throw Error('Сначала укажите URL API в настройках.');const response=await fetch(APP.apiUrl,{method:'POST',redirect:'follow',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...data})});const json=await response.json();if(!json.ok)throw Error(json.error||'Ошибка API');return json.data}
async function loadData(){if(!APP.apiUrl){render();return}try{const data=await api('bootstrap');APP.categories=data.categories;APP.tasks=data.tasks;APP.workCycles=Number(data.workCycles||0);restoreActive(data);render()}catch(e){toast(e.message);render()}}
function restoreActive(data){APP.activeSession=data.activeSession||null;APP.activeDistraction=data.activeDistraction||null;APP.activeTask=APP.tasks.find(t=>t.id===(APP.activeSession?.taskId||data.currentTaskId))||null;if(APP.activeSession){const elapsed=APP.activeDistraction||APP.activeSession.state==='paused'?0:Math.floor((Date.now()-new Date(APP.activeSession.startTime).getTime())/1000);startTicker(Math.max(0,Number(APP.activeSession.remainingSeconds)-elapsed),APP.activeSession.sessionType,false)}}
function showView(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===id));$('#pageTitle').textContent=id==='dashboardView'?'Сегодня':id==='tasksView'?'Задачи':'Отчёты';if(id==='reportsView')loadReports()}
function render(){const task=APP.activeTask;$('#connectionNotice').classList.toggle('hidden',!!APP.apiUrl);$('#currentTaskCard').classList.toggle('hidden',!task);$('#noTaskCard').classList.toggle('hidden',!!task);$('#startBtn').disabled=!task||!!APP.timer;if(task){$('#currentTaskTitle').textContent=task.title;$('#currentTaskMeta').textContent=`${categoryName(task.categoryId)} · План: ${mins(task.plannedMinutes)} · Факт: ${mins(task.actualMinutes)}`}const running=!!APP.timer&&!APP.activeDistraction;$('#startBtn').classList.toggle('hidden',!!APP.timer);$('#pauseBtn').classList.toggle('hidden',!running);$('#resumeBtn').classList.toggle('hidden',!APP.activeDistraction);$('#finishBtn').classList.toggle('hidden',!task);$('#changeTaskBtn').classList.toggle('hidden',!!APP.timer||!task);$('#cycleInfo').textContent=`Рабочий цикл ${Math.min(APP.workCycles%4+1,4)} из 4`;renderTasks()}
function categoryName(id){return APP.categories.find(c=>c.id===id)?.name||'Без категории'}
function renderTasks(){const list=$('#tasksList');if(!APP.tasks.length){list.innerHTML='<article class="empty card"><h2>Задач пока нет</h2><p>Создайте первую задачу для фокус-сессии.</p></article>';return}list.innerHTML=APP.tasks.map(t=>`<article class="card task-card"><div><h2>${esc(t.title)}</h2><p class="meta">${esc(categoryName(t.categoryId))}</p><p class="hours">План: ${mins(t.plannedMinutes)} · Факт: ${mins(t.actualMinutes)}</p></div><span class="status ${t.status==='Done'?'done':''}">${t.status==='Done'?'Готово':t.status==='InProgress'?'В работе':'Новая'}</span><div class="task-buttons">${t.status!=='Done'?`<button class="text-btn" data-select="${t.id}">Выбрать</button>`:''}<button class="text-btn" data-edit="${t.id}">Изменить</button>${t.status!=='Done'?`<button class="text-btn" data-done="${t.id}">Завершить</button>`:''}</div></article>`).join('')}
function updateTimer(seconds,type){const m=Math.floor(seconds/60),s=seconds%60,total=(type==='Work'?APP.settings.work:type==='LongBreak'?APP.settings.longBreak:APP.settings.shortBreak)*60;$('#timerValue').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('#timerMode').textContent=type==='Work'?'РАБОТА':'ПЕРЕРЫВ';$('#timerHint').textContent=type==='Work'?'Сосредоточьтесь на одной задаче':'Отдохните, затем вернитесь к задаче';$('#timerProgress').style.width=`${Math.max(0,Math.min(100,(1-seconds/total)*100))}%`}
function startTicker(seconds,type,save){clearInterval(APP.ticker);APP.timer={seconds,type};updateTimer(seconds,type);APP.ticker=setInterval(async()=>{if(!APP.timer||APP.activeDistraction)return;APP.timer.seconds--;updateTimer(APP.timer.seconds,type);if(APP.timer.seconds<=0){clearInterval(APP.ticker);await completePomodoro()}},1000);if(save)api('startSession',{taskId:APP.activeTask.id,sessionType:type,remainingSeconds:seconds}).then(d=>{APP.activeSession=d}).catch(e=>toast(e.message))}
async function startWork(){if(!APP.activeTask)return;startTicker(APP.settings.work*60,'Work',true);render()}
async function completePomodoro(){try{if(APP.activeSession)await api('endSession',{id:APP.activeSession.id,remainingSeconds:Math.max(0,APP.timer?.seconds||0)});const wasWork=APP.timer?.type==='Work';APP.timer=null;APP.activeSession=null;if(wasWork){APP.workCycles++;await api('setWorkCycles',{workCycles:APP.workCycles});const long=APP.workCycles%4===0;$('#breakTitle').textContent=long?'Длинный отдых':'Рабочий цикл завершён';$('#breakText').textContent=long?'Вы завершили 4 цикла. Сделайте перерыв на 15 минут.':'Время короткого отдыха — 5 минут.';$('#startBreakBtn').dataset.type=long?'LongBreak':'Break';$('#breakDialog').showModal()}else{toast('Перерыв завершён. Можно продолжить работу.')}await loadData()}catch(e){toast(e.message)}}
async function pause(reason){try{clearInterval(APP.ticker);APP.activeDistraction=await api('startDistraction',{taskId:APP.activeTask.id,reason});await api('pauseSession',{id:APP.activeSession.id,remainingSeconds:APP.timer.seconds});render();$('#pauseDialog').close()}catch(e){toast(e.message)}}
async function resume(){try{await api('endDistraction',{id:APP.activeDistraction.id});APP.activeDistraction=null;await api('resumeSession',{id:APP.activeSession.id});startTicker(APP.timer.seconds,APP.timer.type,false);render()}catch(e){toast(e.message)}}
async function selectTask(id){if(APP.timer)return toast('Сначала завершите текущую сессию.');try{const data=await api('selectTask',{id});APP.tasks=data.tasks;APP.activeTask=APP.tasks.find(t=>t.id===id);render();$('#taskPicker').close();toast('Задача выбрана')}catch(e){toast(e.message)}}
function openPicker(){const active=APP.tasks.filter(t=>t.status!=='Done');$('#pickerList').innerHTML=active.length?active.map(t=>`<button class="picker-item" data-select="${t.id}"><strong>${esc(t.title)}</strong><span>${esc(categoryName(t.categoryId))} · ${mins(t.actualMinutes)} из ${mins(t.plannedMinutes)}</span></button>`).join(''):'<p class="muted">Нет незавершённых задач.</p>';$('#taskPicker').showModal()}
function openTask(id=''){const t=APP.tasks.find(x=>x.id===id);$('#taskDialogTitle').textContent=t?'Редактировать задачу':'Новая задача';$('#taskId').value=t?.id||'';$('#taskTitle').value=t?.title||'';$('#taskMinutes').value=t?.plannedMinutes||60;$('#taskCategory').innerHTML=APP.categories.filter(c=>c.active).map(c=>`<option value="${c.id}" ${t?.categoryId===c.id?'selected':''}>${esc(c.name)}</option>`).join('');$('#taskDialog').showModal()}
async function saveTask(e){e.preventDefault();try{const id=$('#taskId').value,data={id,title:$('#taskTitle').value.trim(),categoryId:$('#taskCategory').value,plannedMinutes:Number($('#taskMinutes').value)};const out=await api(id?'updateTask':'createTask',data);APP.tasks=out.tasks;$('#taskDialog').close();render();toast('Задача сохранена')}catch(err){toast(err.message)}}
async function markDone(id){if(!confirm('Завершить задачу?'))return;try{const out=await api('completeTask',{id});APP.tasks=out.tasks;if(APP.activeTask?.id===id)APP.activeTask=null;render();toast('Задача завершена')}catch(e){toast(e.message)}}
async function finishTask(){if(!APP.activeTask||!confirm('Завершить задачу?'))return;try{const taskId=APP.activeTask.id;if(APP.activeDistraction){await api('endDistraction',{id:APP.activeDistraction.id});APP.activeDistraction=null}if(APP.activeSession){await api('endSession',{id:APP.activeSession.id,remainingSeconds:Math.max(0,APP.timer?.seconds||0)});clearInterval(APP.ticker);APP.timer=null;APP.activeSession=null}const out=await api('completeTask',{id:taskId});APP.tasks=out.tasks;APP.activeTask=null;render();toast('Задача завершена')}catch(e){toast(e.message)}}
async function loadReports(){const box=$('#reportsContent');if(!APP.apiUrl){box.innerHTML='<p class="muted">Подключите API, чтобы увидеть отчёты.</p>';return}try{const r=await api('reports');const rows=(items,make)=>items.length?items.map(make).join(''):'<p class="muted">Пока нет данных.</p>';box.innerHTML=`<article class="card report-card"><p class="label">FOCUS RATE</p><div class="metric">${r.focusRate}%</div><p class="muted">Deep Work / всё рабочее время</p></article><article class="card report-card"><h2>По задачам</h2>${rows(r.tasks,x=>`<div class="report-row"><span>${esc(x.title)}<small>План ${mins(x.plannedMinutes)} · Отклонение ${mins(x.actualMinutes-x.plannedMinutes)}</small></span><b>${mins(x.actualMinutes)}</b></div>`)}</article><article class="card report-card"><h2>По категориям</h2>${rows(r.categories,x=>`<div class="report-row"><span>${esc(x.name)}<small>${x.percent}% от рабочего времени</small></span><b>${mins(x.minutes)}</b></div>`)}</article><article class="card report-card"><h2>Отвлечения</h2>${rows(r.distractions,x=>`<div class="report-row"><span>${esc(x.reason)}<small>${x.count} раз</small></span><b>${mins(x.minutes)}</b></div>`)}</article>`}catch(e){box.innerHTML=`<p class="notice">${esc(e.message)}</p>`}}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)return showView(b.dataset.view);if(b.dataset.action==='new-task'){document.querySelectorAll('dialog[open]').forEach(d=>d.close());return openTask()}if(b.dataset.close)return $("#"+b.dataset.close).close();if(b.dataset.select)return selectTask(b.dataset.select);if(b.dataset.edit)return openTask(b.dataset.edit);if(b.dataset.done)return markDone(b.dataset.done)});
$('#startBtn').onclick=startWork;$('#pauseBtn').onclick=()=>$('#pauseDialog').showModal();$('#resumeBtn').onclick=resume;$('#finishBtn').onclick=finishTask;$('#changeTaskBtn').onclick=openPicker;$('#settingsBtn').onclick=()=>$('#settingsDialog').showModal();$('#taskForm').onsubmit=saveTask;$('#reasonList').innerHTML=REASONS.map(x=>`<button data-reason="${x}">${x}</button>`).join('');$('#reasonList').onclick=e=>{const b=e.target.closest('button');if(b)pause(b.dataset.reason)};$('#startBreakBtn').onclick=async e=>{const type=e.currentTarget.dataset.type;$('#breakDialog').close();startTicker((type==='LongBreak'?APP.settings.longBreak:APP.settings.shortBreak)*60,type,true);render()};$('#skipBreakBtn').onclick=()=>{$('#breakDialog').close();render()};$('#settingsForm').onsubmit=e=>{e.preventDefault();if(APP.timer)return toast('Длительность нельзя менять во время активного таймера.');APP.apiUrl=$('#apiUrl').value.trim().replace(/\/$/,'');APP.settings={work:Number($('#workMinutes').value),shortBreak:Number($('#shortBreakMinutes').value),longBreak:Number($('#longBreakMinutes').value)};localStorage.setItem('focusTrackerApiUrl',APP.apiUrl);localStorage.setItem('focusTrackerSettings',JSON.stringify(APP.settings));$('#settingsDialog').close();updateTimer(APP.settings.work*60,'Work');loadData();toast('Настройки сохранены')};$('#reloadBtn').onclick=loadData;$('#apiUrl').value=APP.apiUrl;$('#workMinutes').value=APP.settings.work;$('#shortBreakMinutes').value=APP.settings.shortBreak;$('#longBreakMinutes').value=APP.settings.longBreak;updateTimer(APP.settings.work*60,'Work');loadData();
