/** Focus Tracker 2.0 — Google Apps Script backend. */
const SPREADSHEET_ID = 'PASTE_YOUR_GOOGLE_SHEET_ID_HERE';
const TZ = 'Asia/Tashkent';
const SHEETS = {
  categories:['id','name','active'], tasks:['id','title','categoryId','plannedMinutes','actualMinutes','status','createdAt','updatedAt'],
  sessions:['id','taskId','startTime','endTime','durationMinutes','sessionType','remainingSeconds','initialSeconds','state'],
  distractions:['id','taskId','startTime','endTime','durationMinutes','reason','state'], settings:['key','value'],
  timeEntries:['id','startTime','endTime','durationMinutes','categoryId','taskId','notes','source']
};
const DEFAULT_CATEGORIES=['Deep Work','Аналитика / ТЗ','Планирование','Встречи','Рабочие чаты','Комментарии в Битрикс','Почта','Учеба','Администрирование'];
function doGet(e){return respond(handle({action:e.parameter.action||'bootstrap'}))} function doPost(e){try{return respond(handle(JSON.parse(e.postData.contents||'{}')))}catch(err){return respond({ok:false,error:err.message})}} function respond(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function handle(p){try{setup_();let data;switch(p.action){case 'bootstrap':data=bootstrap_();break;case 'createTask':case 'updateTask':data=saveTask_(p);break;case 'completeTask':data=completeTask_(p.id);break;case 'selectTask':data=selectTask_(p.id);break;case 'startSession':data=startSession_(p);break;case 'pauseSession':data=updateSession_(p.id,{remainingSeconds:p.remainingSeconds,state:'paused'});break;case 'resumeSession':data=updateSession_(p.id,{state:'active'});break;case 'endSession':data=endSession_(p);break;case 'startDistraction':data=startDistraction_(p);break;case 'endDistraction':data=endDistraction_(p.id);break;case 'setWorkCycles':setSetting_('workCycles',p.workCycles);data={};break;case 'createTimeEntries':data=createTimeEntries_(p);break;case 'timeEntries':data=timeEntries_(p);break;case 'reports':data=reports_(p.date);break;default:throw Error('Unknown action')}return {ok:true,data:data}}catch(err){return {ok:false,error:err.message}}}
function ss_(){if(SPREADSHEET_ID==='PASTE_YOUR_GOOGLE_SHEET_ID_HERE')throw Error('Set SPREADSHEET_ID in google-apps-script.gs');return SpreadsheetApp.openById(SPREADSHEET_ID)}
function setup_(){const ss=ss_();Object.keys(SHEETS).forEach(n=>{let sh=ss.getSheetByName(n);if(!sh){sh=ss.insertSheet(n);sh.appendRow(SHEETS[n]);sh.setFrozenRows(1)}else ensureColumns_(sh,SHEETS[n])});if(!all_('categories').length)DEFAULT_CATEGORIES.forEach(name=>ss.getSheetByName('categories').appendRow([id_(),name,true]));migrateSessions_()}
function ensureColumns_(sh,headers){const existing=sh.getRange(1,1,1,Math.max(1,sh.getLastColumn())).getValues()[0];headers.forEach(h=>{if(existing.indexOf(h)<0){sh.getRange(1,sh.getLastColumn()+1).setValue(h);existing.push(h)}})} function all_(name){const sh=ss_().getSheetByName(name);if(sh.getLastRow()<2)return [];const v=sh.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='' )).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function id_(){return Utilities.getUuid()} function now_(){return new Date().toISOString()} function find_(n,id){return all_(n).find(x=>x.id===id)} function headers_(n){const sh=ss_().getSheetByName(n);return sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0]} function append_(n,obj){ss_().getSheetByName(n).appendRow(headers_(n).map(k=>obj[k]===undefined||obj[k]===null?'':obj[k]));return obj}
function patch_(n,id,fields){const sh=ss_().getSheetByName(n),vals=sh.getDataRange().getValues(),col=vals[0];for(let i=1;i<vals.length;i++)if(vals[i][0]===id){Object.keys(fields).forEach(k=>vals[i][col.indexOf(k)]=fields[k]);sh.getRange(i+1,1,1,col.length).setValues([vals[i]]);return Object.assign(Object.fromEntries(col.map((x,j)=>[x,vals[i][j]])),fields)}throw Error('Record not found')}
function taskView_(t){return Object.assign({},t,{plannedMinutes:Number(t.plannedMinutes),actualMinutes:Number(t.actualMinutes)})} function tasks_(){return all_('tasks').map(taskView_).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)))} function saveTask_(p){if(!p.title||!p.categoryId||!Number(p.plannedMinutes))throw Error('Заполните все поля задачи');if(p.id)patch_('tasks',p.id,{title:p.title,categoryId:p.categoryId,plannedMinutes:Number(p.plannedMinutes),updatedAt:now_()});else append_('tasks',{id:id_(),title:p.title,categoryId:p.categoryId,plannedMinutes:Number(p.plannedMinutes),actualMinutes:0,status:'New',createdAt:now_(),updatedAt:now_()});return {tasks:tasks_()}} function completeTask_(id){patch_('tasks',id,{status:'Done',updatedAt:now_()});setSetting_('currentTaskId','');return {tasks:tasks_()}} function selectTask_(id){patch_('tasks',id,{status:'InProgress',updatedAt:now_()});setSetting_('currentTaskId',id);return {tasks:tasks_()}}
function active_(n){return all_(n).find(x=>x.state==='active'||x.state==='paused')||null} function startSession_(p){if(active_('sessions'))throw Error('Уже есть активная сессия');const seconds=Number(p.remainingSeconds),x={id:id_(),taskId:p.taskId,startTime:now_(),endTime:'',durationMinutes:0,sessionType:p.sessionType||'Work',remainingSeconds:seconds,initialSeconds:seconds,state:'active'};append_('sessions',x);return x} function updateSession_(id,fields){return patch_('sessions',id,fields)}
function endSession_(p){const s=find_('sessions',p.id);if(!s)throw Error('Сессия не найдена');const seconds=Math.max(0,Number(p.remainingSeconds||0)),end=now_(),duration=Math.round((Number(s.initialSeconds||s.remainingSeconds||0)-seconds)/60);patch_('sessions',p.id,{endTime:end,durationMinutes:duration,state:'ended',remainingSeconds:seconds});if(s.sessionType==='Work')createPomodoroEntry_(s,end,duration);recalcTask_(s.taskId);setSetting_('lastActivityTimestamp',end);return {id:p.id}} function createPomodoroEntry_(s,end,duration){const marker='Pomodoro session: '+s.id;if(all_('timeEntries').some(x=>x.notes===marker))return;const task=find_('tasks',s.taskId);if(task)append_('timeEntries',{id:id_(),startTime:s.startTime,endTime:end,durationMinutes:Math.max(0,duration),categoryId:task.categoryId,taskId:s.taskId,notes:marker,source:'Pomodoro'})} function migrateSessions_(){all_('sessions').filter(s=>s.sessionType==='Work'&&s.state==='ended'&&s.endTime).forEach(s=>createPomodoroEntry_(s,s.endTime,Number(s.durationMinutes||0)))}
function startDistraction_(p){if(active_('distractions'))throw Error('Отвлечение уже активно');const x={id:id_(),taskId:p.taskId,startTime:now_(),endTime:'',durationMinutes:0,reason:p.reason,state:'active'};append_('distractions',x);return x} function endDistraction_(id){const d=find_('distractions',id);if(!d)throw Error('Отвлечение не найдено');const duration=Math.max(0,Math.round((Date.now()-new Date(d.startTime).getTime())/60000));return patch_('distractions',id,{endTime:now_(),durationMinutes:duration,state:'ended'})} function recalcTask_(id){const total=all_('sessions').filter(s=>s.taskId===id&&s.sessionType==='Work'&&s.state==='ended').reduce((a,s)=>a+Number(s.durationMinutes||0),0);patch_('tasks',id,{actualMinutes:total,updatedAt:now_()})}
function setting_(key){const row=all_('settings').find(x=>x.key===key);return row?row.value:''} function setSetting_(key,value){const x=all_('settings').find(x=>x.key===key);if(x)patch_('settings',x.key,{value:String(value)});else append_('settings',{key:key,value:String(value)})} function dayKey_(d){return Utilities.formatDate(new Date(d),TZ,'yyyy-MM-dd')} function dayBounds_(date){const d=date||dayKey_(new Date());const start=new Date(d+'T00:00:00+05:00');return {start:start,end:new Date(start.getTime()+86400000)}} function entriesForDay_(date){const b=dayBounds_(date);return all_('timeEntries').filter(x=>new Date(x.endTime)>b.start&&new Date(x.startTime)<b.end)} function bootstrap_(){return {categories:all_('categories').map(c=>Object.assign(c,{active:String(c.active)==='true'})),tasks:tasks_(),activeSession:active_('sessions'),activeDistraction:active_('distractions'),currentTaskId:setting_('currentTaskId'),workCycles:setting_('workCycles'),lastActivityTimestamp:setting_('lastActivityTimestamp')}} function timeEntries_(p){return {entries:entriesForDay_(p.date).sort((a,b)=>new Date(b.startTime)-new Date(a.startTime)),lastActivityTimestamp:setting_('lastActivityTimestamp')}}
function overlap_(start,end){return all_('timeEntries').some(x=>new Date(x.startTime)<end&&new Date(x.endTime)>start)} function createTimeEntries_(p){if(active_('sessions'))throw Error('Нельзя вести ручной учёт во время активной Pomodoro-сессии');const start=new Date(p.startTime),end=new Date(p.endTime),entries=p.entries||[];if(isNaN(start)||isNaN(end)||end<=start)throw Error('Проверьте начало и конец интервала');const total=Math.round((end-start)/60000),sum=entries.reduce((a,x)=>a+Number(x.durationMinutes||0),0);if(!entries.length||sum!==total)throw Error('Сумма активностей должна точно совпадать с длительностью интервала');if(overlap_(start,end))throw Error('Этот интервал пересекается с уже учтённым временем');let cursor=new Date(start);entries.forEach(x=>{if(!x.categoryId||!Number(x.durationMinutes)||Number(x.durationMinutes)<1)throw Error('У каждой активности должны быть категория и длительность');const next=new Date(cursor.getTime()+Number(x.durationMinutes)*60000);append_('timeEntries',{id:id_(),startTime:cursor.toISOString(),endTime:next.toISOString(),durationMinutes:Number(x.durationMinutes),categoryId:x.categoryId,taskId:x.taskId||'',notes:x.notes||'',source:'ManualLog'});cursor=next});setSetting_('lastActivityTimestamp',end.toISOString());return {entries:timeEntries_({date:dayKey_(end)})}}
function reports_(date){const b=dayBounds_(date),entries=entriesForDay_(date),categories=all_('categories'),tasks=tasks_(),total=entries.reduce((a,x)=>a+Number(x.durationMinutes||0),0),deepIds=categories.filter(c=>c.name==='Deep Work').map(c=>c.id),deep=entries.filter(x=>deepIds.indexOf(x.categoryId)>=0).reduce((a,x)=>a+Number(x.durationMinutes||0),0),distractions=all_('distractions').filter(d=>d.state==='ended'&&new Date(d.endTime)>b.start&&new Date(d.startTime)<b.end),distractionMinutes=distractions.reduce((a,d)=>a+Number(d.durationMinutes||0),0),cat=categories.map(c=>{const minutes=entries.filter(x=>x.categoryId===c.id).reduce((a,x)=>a+Number(x.durationMinutes||0),0);return {name:c.name,minutes:minutes,percent:total?Math.round(minutes/total*100):0}}).filter(x=>x.minutes),taskMap={};entries.filter(x=>x.taskId).forEach(x=>taskMap[x.taskId]=(taskMap[x.taskId]||0)+Number(x.durationMinutes||0));const taskRows=tasks.filter(t=>taskMap[t.id]).map(t=>Object.assign({},t,{actualMinutes:taskMap[t.id]})),sources=['Pomodoro','ManualLog'].map(source=>({source:source,minutes:entries.filter(x=>x.source===source).reduce((a,x)=>a+Number(x.durationMinutes||0),0)})),reasonMap={};distractions.forEach(d=>{if(!reasonMap[d.reason])reasonMap[d.reason]={reason:d.reason,count:0,minutes:0};reasonMap[d.reason].count++;reasonMap[d.reason].minutes+=Number(d.durationMinutes||0)});return {date:date||dayKey_(new Date()),tasks:taskRows,categories:cat,distractions:Object.values(reasonMap),sources:sources,focusRate:deep+distractionMinutes?Math.round(deep/(deep+distractionMinutes)*100):0,coverageRate:Math.round(total/1440*1000)/10,unlogged:unlogged_(entries,b),totalMinutes:total}}
function unlogged_(entries,b){const ranges=entries.map(x=>({start:Math.max(new Date(x.startTime).getTime(),b.start.getTime()),end:Math.min(new Date(x.endTime).getTime(),b.end.getTime())})).sort((a,b)=>a.start-b.start);let cursor=b.start.getTime(),out=[];ranges.forEach(r=>{if(r.start>cursor)out.push({startTime:new Date(cursor).toISOString(),endTime:new Date(r.start).toISOString(),durationMinutes:Math.round((r.start-cursor)/60000)});cursor=Math.max(cursor,r.end)});if(cursor<b.end.getTime())out.push({startTime:new Date(cursor).toISOString(),endTime:b.end.toISOString(),durationMinutes:Math.round((b.end.getTime()-cursor)/60000)});return out.filter(x=>x.durationMinutes>0)}
