/** Focus Tracker Google Apps Script backend. Set the spreadsheet ID once, then deploy as Web App. */
const SPREADSHEET_ID = 'PASTE_YOUR_GOOGLE_SHEET_ID_HERE';
const SHEETS = {categories:['id','name','active'],tasks:['id','title','categoryId','plannedMinutes','actualMinutes','status','createdAt','updatedAt'],sessions:['id','taskId','startTime','endTime','durationMinutes','sessionType','remainingSeconds','initialSeconds','state'],distractions:['id','taskId','startTime','endTime','durationMinutes','reason','state'],settings:['key','value']};
const DEFAULT_CATEGORIES=['Deep Work','Аналитика / ТЗ','Планирование','Встречи','Рабочие чаты','Комментарии в Битрикс','Почта','Учеба','Администрирование'];
function doGet(e){return respond(handle({action:e.parameter.action||'bootstrap'}))} function doPost(e){try{return respond(handle(JSON.parse(e.postData.contents||'{}')))}catch(err){return respond({ok:false,error:err.message})}}
function respond(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}
function handle(p){try{setup_();let data;switch(p.action){case 'bootstrap':data=bootstrap_();break;case 'createTask':data=saveTask_(p);break;case 'updateTask':data=saveTask_(p);break;case 'completeTask':data=completeTask_(p.id);break;case 'selectTask':data=selectTask_(p.id);break;case 'startSession':data=startSession_(p);break;case 'pauseSession':data=updateSession_(p.id,{remainingSeconds:p.remainingSeconds,state:'paused'});break;case 'resumeSession':data=updateSession_(p.id,{state:'active'});break;case 'endSession':data=endSession_(p);break;case 'startDistraction':data=startDistraction_(p);break;case 'endDistraction':data=endDistraction_(p.id);break;case 'setWorkCycles':setSetting_('workCycles',p.workCycles);data={};break;case 'reports':data=reports_();break;default:throw Error('Unknown action');}return {ok:true,data:data}}catch(err){return {ok:false,error:err.message}}}
function ss_(){if(SPREADSHEET_ID==='PASTE_YOUR_GOOGLE_SHEET_ID_HERE')throw Error('Set SPREADSHEET_ID in google-apps-script.gs');return SpreadsheetApp.openById(SPREADSHEET_ID)}
function setup_(){const ss=ss_();Object.keys(SHEETS).forEach(n=>{let sh=ss.getSheetByName(n);if(!sh){sh=ss.insertSheet(n);sh.appendRow(SHEETS[n]);sh.setFrozenRows(1)}});if(all_('categories').length===0){const sh=ss_().getSheetByName('categories');DEFAULT_CATEGORIES.forEach(name=>sh.appendRow([id_(),name,true]))}}
function all_(name){const sh=ss_().getSheetByName(name),v=sh.getDataRange().getValues(),h=v.shift();return v.filter(r=>r.some(x=>x!=='' )).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]])))}
function id_(){return Utilities.getUuid()} function now_(){return new Date().toISOString()} function find_(n,id){return all_(n).find(x=>x.id===id)}
function append_(n,obj){const h=SHEETS[n];ss_().getSheetByName(n).appendRow(h.map(k=>obj[k]===undefined||obj[k]===null?'':obj[k]));return obj}
function patch_(n,id,fields){const sh=ss_().getSheetByName(n),vals=sh.getDataRange().getValues(),col=vals[0];for(let i=1;i<vals.length;i++)if(vals[i][0]===id){Object.keys(fields).forEach(k=>vals[i][col.indexOf(k)]=fields[k]);sh.getRange(i+1,1,1,col.length).setValues([vals[i]]);return Object.assign(Object.fromEntries(col.map((x,j)=>[x,vals[i][j]])),fields)}throw Error('Record not found')}
function taskView_(t){return Object.assign({},t,{plannedMinutes:Number(t.plannedMinutes),actualMinutes:Number(t.actualMinutes)})}
function tasks_(){return all_('tasks').map(taskView_).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}
function saveTask_(p){if(!p.title||!p.categoryId||!Number(p.plannedMinutes))throw Error('Заполните все поля задачи');if(p.id)patch_('tasks',p.id,{title:p.title,categoryId:p.categoryId,plannedMinutes:Number(p.plannedMinutes),updatedAt:now_()});else append_('tasks',{id:id_(),title:p.title,categoryId:p.categoryId,plannedMinutes:Number(p.plannedMinutes),actualMinutes:0,status:'New',createdAt:now_(),updatedAt:now_()});return {tasks:tasks_()}}
function completeTask_(id){patch_('tasks',id,{status:'Done',updatedAt:now_()});setSetting_('currentTaskId','');return {tasks:tasks_()}} function selectTask_(id){patch_('tasks',id,{status:'InProgress',updatedAt:now_()});setSetting_('currentTaskId',id);return {tasks:tasks_()}}
function active_(n){return all_(n).find(x=>x.state==='active'||x.state==='paused')||null}
function startSession_(p){if(active_('sessions'))throw Error('Уже есть активная сессия');const seconds=Number(p.remainingSeconds);const x={id:id_(),taskId:p.taskId,startTime:now_(),endTime:'',durationMinutes:0,sessionType:p.sessionType||'Work',remainingSeconds:seconds,initialSeconds:seconds,state:'active'};append_('sessions',x);return x}
function updateSession_(id,fields){return patch_('sessions',id,fields)}
function endSession_(p){const s=find_('sessions',p.id);if(!s)throw Error('Сессия не найдена');const seconds=Math.max(0,Number(p.remainingSeconds||0));const duration=Math.round((Number(s.initialSeconds||s.remainingSeconds||0)-seconds)/60);patch_('sessions',p.id,{endTime:now_(),durationMinutes:duration,state:'ended',remainingSeconds:seconds});recalcTask_(s.taskId);return {id:p.id}}
function startDistraction_(p){if(active_('distractions'))throw Error('Отвлечение уже активно');const x={id:id_(),taskId:p.taskId,startTime:now_(),endTime:'',durationMinutes:0,reason:p.reason,state:'active'};append_('distractions',x);return x}
function endDistraction_(id){const d=find_('distractions',id);if(!d)throw Error('Отвлечение не найдено');const duration=Math.max(0,Math.round((Date.now()-new Date(d.startTime).getTime())/60000));return patch_('distractions',id,{endTime:now_(),durationMinutes:duration,state:'ended'})}
function recalcTask_(id){const total=all_('sessions').filter(s=>s.taskId===id&&s.sessionType==='Work'&&s.state==='ended').reduce((a,s)=>a+Number(s.durationMinutes||0),0);patch_('tasks',id,{actualMinutes:total,updatedAt:now_()})}
function setting_(key){const row=all_('settings').find(x=>x.key===key);return row?row.value:'0'} function setSetting_(key,value){const x=all_('settings').find(x=>x.key===key);if(x)patch_('settings',x.key,{value:String(value)});else append_('settings',{key:key,value:String(value)})}
function bootstrap_(){return {categories:all_('categories').map(c=>Object.assign(c,{active:String(c.active)==='true'})),tasks:tasks_(),activeSession:active_('sessions'),activeDistraction:active_('distractions'),currentTaskId:setting_('currentTaskId'),workCycles:setting_('workCycles')}}
function reports_(){const tasks=tasks_(),categories=all_('categories'),sessions=all_('sessions').filter(s=>s.sessionType==='Work'&&s.state==='ended'),total=sessions.reduce((a,s)=>a+Number(s.durationMinutes||0),0),deepIds=categories.filter(c=>c.name==='Deep Work').map(c=>c.id),deep=tasks.filter(t=>deepIds.includes(t.categoryId)).reduce((a,t)=>a+t.actualMinutes,0);const cat=categories.map(c=>{const minutes=tasks.filter(t=>t.categoryId===c.id).reduce((a,t)=>a+t.actualMinutes,0);return {name:c.name,minutes:minutes,percent:total?Math.round(minutes/total*100):0}}).filter(x=>x.minutes);const map={};all_('distractions').filter(d=>d.state==='ended').forEach(d=>{if(!map[d.reason])map[d.reason]={reason:d.reason,count:0,minutes:0};map[d.reason].count++;map[d.reason].minutes+=Number(d.durationMinutes||0)});return {tasks:tasks,categories:cat,distractions:Object.values(map),focusRate:total?Math.round(deep/total*100):0}}
